### ISSUE TITLE
Web3 Failover String does not like the Old Failover String Format, and causes the beacon chain to crash

### ISSUE THREAD

**Issue by JHGrove3** [dappnode/DAppNodePackage-prysm-prater#60]
**Describe the bug**

Upgraded to Version: 1.0.5 (v2.1.2 upstream)

After update, the Prysm Prater beacon chain stopped synching

Noticed that it kept crashing shortly after saying it was going to try the failover provider.

On a hunch, deleted my old web3 failover string, which was living in the EXTRA_OPTS field.  The old string looked like this:

--fallback-web3provider=https://eth-goerli.alchemyapi.io/v2/API-SECRET-GOES-HERE --fallback-web3provider=https://goerli.infura.io/v3/API-SECRET-GOES-HERE

After deleting that string, the beacon chain began to sync properly. When it finished syncing, the test validators began working properly, too.

**DAppNode version:**

Before filing a new topic, please provide the following information.
Core DAppNode Packages versions

    bind.dnp.dappnode.eth: 0.2.6
    core.dnp.dappnode.eth: 0.2.54
    dappmanager.dnp.dappnode.eth: 0.2.49, commit: 14f56e8e
    https.dnp.dappnode.eth: 0.1.3
    ipfs.dnp.dappnode.eth: 0.2.16
    wifi.dnp.dappnode.eth: 0.2.8
    wireguard.dnp.dappnode.eth: 0.1.1

System info

    dockerComposeVersion: 1.25.5
    dockerServerVersion: 20.10.6
    dockerCliVersion: 20.10.6
    os: debian
    versionCodename: bullseye
    architecture: amd64
    kernel: 5.10.0-8-amd64
    Disk usage: 78%

**Additional context**

**Comment by etherni** [comment]
I believe I am experiencing a sort of similar issue.
I attempted to configure the Prysm Prater package to use "_backup web 3 provider_" AND "_Checkpoint for fast sync_"

According to the Package Config these are the suggested connection strings:
![image](https://user-images.githubusercontent.com/4120215/172022534-13c0b6a9-23cf-4213-8c39-3b6437803f3e.png)

My existing project on the Infura has connection template which is different due to the project being **ETH** rather than **ETH2**:
`https://mainnet.infura.io/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

I created a new ETH2 project on Infura and noticed a new connection string template:
https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@eth2-beacon-prater.infura.io (**Prater**)
https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@eth2-beacon-mainnet.infura.io (**Mainnet**)

So, from the screenshot above it only matches "_Checkpoint for fast sync_". So I used new connection string to set up Checkpoint for fast sync, but it failed. I can see requests reaching Infura, but also see errors in the log on my DappNode

Infura:
![image](https://user-images.githubusercontent.com/4120215/172022746-967787b4-71ff-4aad-ac86-fb018d92c035.png)

Log:
```
time="2022-06-04 19:15:20" level=error msg="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.33.0.7:4000: connect: connection refused"" prefix=validator
time="2022-06-04 19:15:20" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.33.0.7:4000: connect: connection refused"" prefix=validator
```
I cannot find in Infura connection string for the _backup web3 provider_
I attempted to just include my Project ID instead of "X" in the provided template, but wasn't able to save that setting:
![image](https://user-images.githubusercontent.com/4120215/172022868-e14a50cb-8284-45db-8d92-5d8a5cf271a7.png)

Can someone help me to configure Infura failover for the Prysm Prater package?

**Comment by pablomendezroyo** [comment]
@etherni thank you for the report!

> I created a new **ETH2** project on Infura and noticed a new connection string template:

The mainnet naming was a typo, you should always use prater endpoint. You can use the same RPC endpoint for the checkpoint sync and for the web3 fallback provider

This typo was fixed by https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/70

**Comment by pablomendezroyo** [comment]
@JHGrove3 Thanks for the report!

> After update, the Prysm Prater beacon chain stopped synching

This was a bug due to a double flag declaration. Fixed by https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/69

**Comment by etherni** [comment]
Thank you for fixing the typo but Infura failover doesn't work. Same "no service" message as before:
![image](https://user-images.githubusercontent.com/4120215/172411099-e62a03d7-a278-4fde-974f-c3260ca1d598.png)
